### ISSUE TITLE
Join tables with overlapping rows

### ISSUE THREAD

**Issue by summerela** [cloudera/ibis-notebooks#9]
Hello-

I'm trying to join two tables that contain overlapping rows. 

     join_expression = [test_vars.chr == clinvar.chrom, test_vars.pos == clinvar.pos, 
         test_vars.ref == clinvar.ref, test_vars.alt == clinvar.alt]

    test_clinvar = test_vars.inner_join(clinvar, join_expression )

Your tutorial states: 

'Most importantly, depending on your schemas, the joined tables may include overlapping column names that could create a conflict if not addressed directly.'

But I cannot see any instructions on how to 'address this directly' and am getting the following error: 

    RelationError: Joined tables have overlapping names: ['filter', 'qual', 'alt', 'ref', 'pos']

I also tried creating a subset that contains just the columns I need to join on, and the column I wanted to return from the clinvar table: 

    clin_subset = clinvar['clin_sig', 'chrom', 'pos', 'ref', 'alt']

    join_expression = [test_vars.chr == clin_subset.chrom, test_vars.pos == clin_subset.pos,  
        test_vars.ref == clin_subset.ref, test_vars.alt == clin_subset.alt]

    test_clinvar = test_vars.inner_join(clin_subset, join_expression )

But I still get the overlapping columns error: 

    RelationError: Joined tables have overlapping names: ['alt', 'ref', 'pos']

**Comment by wesm** [comment]
The best place for questions is

https://groups.google.com/a/cloudera.org/forum/#!forum/ibis-user

I suggest using the join + projection pattern described here http://docs.ibis-project.org/sql.html#join-projection

I have intended to add some prefix/suffix tools to make overlapping names in the left and right tables unique, but I haven't implemented it yet: https://github.com/cloudera/ibis/issues/680
